/*
 * This source file was generated by the Gradle 'init' task
 */
package projecto_gj;

import projecto_gj.sistema.Sistema;

public class App {

    public static void main(String[] args) {
        Sistema.inicializarApp();
        Sistema.mostrarMenu();
    }
}

